# Generated by Django 4.2.5 on 2023-10-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulap', '0004_alter_meeting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
