# Generated by Django 4.2.5 on 2023-10-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edulap', '0005_alter_meeting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='start_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edulap.customer'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
