# Generated by Django 4.2.5 on 2023-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulap', '0006_courses_start_at_courses_user_meeting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='start_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
