# Generated by Django 4.2.5 on 2023-10-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulap', '0007_alter_courses_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='startDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
