# Generated by Django 4.2.5 on 2023-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulap', '0008_meeting_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
