# Generated by Django 4.2.5 on 2023-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulap', '0009_alter_meeting_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
    ]
