# Generated by Django 4.2.5 on 2023-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulap', '0010_alter_meeting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
